version: "3"
services:
  db:
    image: postgres:latest
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: yarn start
    ports:
      - "8000:3000"
volumes:
  postgres_data:
  bundle_data: